// OPERATOR CLASS IS USED TO GET INSTANCES OF DATABASES.
const operatorClass = require ('../classes/operator');

// THIS FILE CONTAINS COMMON VARIABLES THAT WE CAN SHARE BETWEEN CLASSES.
const store = require ('../store');

// USER CLASS CONTAINS USER-RELATED ACTIVITIES LIKE GETTING USER PROFILE INFORMATION FROM USER TABLE,
// GETTING THE USER ROLE, AUTHENTICATING USER, ENCRYPTING PASSWORDS ETC.
const userClass = require ('../classes/user');

// STARTING Generic CLASS.
class Generic
{
	// PRIVATE VARIABLE TO HOLD THE INSTANCE OF OPERATOR CLASS.
	// WE WILL USE THIS CLASS TO GET INSTANCES OF DIFFERENT DATABASES TO COMMUNICATE WITH THEM.
	#operator;
	
	// PUBLIC VARIABLE TO HOLD INSTANCE OF USER CLASS. WE WILL USE IT TO GET USER RELATED PROPERTIES,
	// FOR EXAMPLE, GETTING USER PROFILE INFORMATION.
	userClass;
	
	// DEFINE CLASS INSTANCES; THIS WILL BE THE FIRST FUNCTION TO BE EXECUTED WHEN THIS CLASS LOADS.
	constructor()
	{
		this.#operator = new operatorClass(); // CREATING A NEW INSTANCE OF OPERATOR CLASS SO WE CAN USE ITS OBJECTS.
	}
	
	// THIS FUNCTION WILL HANDLE GET/POST REQUESTS MADE BY USER FROM THE ANGULAR APPLICATION RUNNING ON CLIENT SIDE.
	handleRequests (app)
	{
		// HANDLING REQUEST FROM CLIENT DURING THE APP INITIALIZATION.
		app.get ('/api/getAppInitialData', (req, res) =>
		{
			let data= {}; 
			data ["sitevariables"] = store.siteVariables; // ADDING SITE VARIABLE DATA INTO ARRAY.
			data ["sitemessages"] = store.siteMessages; // ADDING MESSAGES TO DATA ARRAY.
			res.send(data); // SENDING DATA TO CLIENT.
		});


	}
}

// EXPORTING THIS CLASS SO OTHER CLASSES CAN IMPORT AND USE IT.
module.exports = Generic;
