// INCLUDING DATABASE CLASS INTO THIS CLASS SO WE CAN PERFORM INSERT/UPDATE/DELETE OPERATIONS ON THE DATABASE.
const dbClass = require('../database/db');

// STARTING THE Operator CLASS.
class Operator
{
	#Db; // PRIVATE VARIABLE TO HOLD INSTANCE OF DB CLASS.
	
	// CLASS CONSTRUCTOR; THIS WILL BE THE FIRST FUNCTION TO BE EXECUTED WHEN THIS CLASS LOADS.
	constructor ()
	{
		this.#Db = new dbClass(); // CREATING A NEW INSTANCE OF MAIN DB CLASS.
	}
	
	// RETURNS THE INSTANCE OF MAIN DB CLASS. SO ANY KIND OF UPDATE/DELETE/INSERT
	// ACTION CAN BE PERFORMED ON MAIN DATABASE.
	getDbInstance()
	{
		return this.#Db;
	}
}

// EXPORTING THIS CLASS SO OTHER CLASSES CAN IMPORT AND USE IT.
module.exports = Operator;
